parameters:
    siphoc_pdf.basepath: ~
    siphoc_pdf.options: []
    siphoc_pdf.binary: '/usr/local/bin/wkhtmltopdf'

services:
    buzz.request:
        class: Buzz\Message\Request

    buzz.response:
        class: Buzz\Message\Response

    buzz.client:
        class: Buzz\Client\FileGetContents

    knp.snappy.pdf:
        class: Knp\Snappy\Pdf
        arguments: [ %KijhoTechnologies_pdf.binary%, %KijhoTechnologies_pdf.options% ]

    siphoc.buzz_request_handler:
        class: kijhoTechnologies\PdfBundle\Util\BuzzRequestHandler
        arguments: [ @buzz.request, @buzz.response, @buzz.client ]

    siphoc.pdf.css_to_html:
        class: kijhoTechnologies\PdfBundle\Converter\CssToHTML
        arguments: [ @siphoc.buzz_request_handler ]
        calls:
            - [ setBasePath, [ %KijhoTechnologies_pdf.basepath% ] ]

    siphoc.pdf.css_path_to_url:
        class: kijhoTechnologies\PdfBundle\Converter\CssPathToUrl

    siphoc.pdf.js_to_html:
        class: kijhoTechnologies\PdfBundle\Converter\JSToHTML
        arguments: [ @KijhoTechnologies.buzz_request_handler ]
        calls:
            - [ setBasePath, [ %KijhoTechnologies_pdf.basepath% ] ]
