parameters:
    frcho_pdf.basepath: ~
    frcho_pdf.options: []
    frcho_pdf.binary: '/usr/local/bin/wkhtmltopdf'

services:
    buzz.request:
        class: Buzz\Message\Request

    buzz.response:
        class: Buzz\Message\Response

    buzz.client:
        class: Buzz\Client\FileGetContents

    knp.snappy.pdf:
        class: Knp\Snappy\Pdf
        arguments: [ %frcho_pdf.binary%, %frcho_pdf.options% ]

    frcho.buzz_request_handler:
        class: Frcho\PdfBundle\Util\BuzzRequestHandler
        arguments: [ @buzz.request, @buzz.response, @buzz.client ]

    frcho.pdf.css_to_html:
        class: Frcho\PdfBundle\Converter\CssToHTML
        arguments: [ @frcho.buzz_request_handler ]
        calls:
            - [ setBasePath, [ %frcho_pdf.basepath% ] ]

    frcho.pdf.css_path_to_url:
        class: Frcho\PdfBundle\Converter\CssPathToUrl

    frcho.pdf.js_to_html:
        class: Frcho\PdfBundle\Converter\JSToHTML
        arguments: [ @frcho.buzz_request_handler ]
        calls:
            - [ setBasePath, [ %frcho_pdf.basepath% ] ]
